name = "summer-forest-d5e5"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 生产环境变量 (通过wrangler secret设置敏感信息)
[vars]
ENVIRONMENT = "production"
DATABASE_URL = "libsql://jjticket-kuang-sheng.aws-us-east-1.turso.io"

# 注意：DATABASE_AUTH_TOKEN 需要通过 wrangler secret 命令设置
# 运行: wrangler secret put DATABASE_AUTH_TOKEN 